### ISSUE TITLE
Not working on release mode

### ISSUE THREAD

**Issue by shashankmeddo** [razorpay/razorpay-android-sample-app#117]
Unable to start activity ComponentInfo{in.meddo.patient/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/base.apk"],nativeLibraryDirectories=[/data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/lib/arm, /data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/base.apk"],nativeLibraryDirectories=[/data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/lib/arm, /data/app/in.meddo.patient-ZASQBsxdoUfuLsHGfUNbsQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

**Comment by sumedht** [comment]
@shashankmeddo Which version u r using? R u facing the same issue in the sample app?

**Comment by abhijeet971992** [comment]
I am also facing the same issue. The payment gateway activity opens and runs smoothly in Debug mode. In release mode, the app crashes. Following is the stacktrace I got from Crashlytics:
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.infonotics.stocklytics/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/lib/arm, /data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]

Caused by java.lang.ClassNotFoundException
Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/lib/arm, /data/app/com.infonotics.stocklytics-GxqQyOIQhZYi6W2A6UXBLg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]

**Comment by neha-kashware** [comment]
Try this one, i was facing the same issue and [this](https://stackoverflow.com/questions/58706014/razorpay-crashes-on-payment-page-didnt-find-class-com-razorpay-d-1-in-flut) solved it

**Comment by sumedht** [comment]
@shashankmeddo @abhijeet971992 @neha-kashware 
U need to add proguard rules as mention in documents. Also, update to the latest version of SDK 1.6.3
https://razorpay.com/docs/payment-gateway/android-integration/custom/proguard/
