### ISSUE TITLE
Please update the docs to mention that keyId needs to be in manifest.xml

### ISSUE THREAD

**Issue by nitinsurana** [razorpay/razorpay-android-sample-app#175]
According to the current [docs](https://razorpay.com/docs/payment-gateway/android-integration/standard/), keyid is set inside the activity. But this sample app clearly demonstrates & works when the api key id is set in manifest.xml instead.

Please update the docs for the same.

PS: Thanks for this app; it's very helpful.

**Comment by vivekshindhe** [comment]
@nitinsurana Thanks for reaching out to us. Could you maybe send us the logs you are getting for this error? The library was developed so that the key_id can be set from either AndroidManifest of an Activity of the user's choice. 

Can you please try with this once, 

> final Checkout co = new Checkout();
> co.setKeyID(key_id);

and remove the metadata key from the Manifest file completely. 

We are not able to reproduce this issue on our end. It'd be very helpful if you could send us the logs you are getting for this if it still doesn't work.

**Comment by nitinsurana** [comment]
I'm no longer able to reproduce it; strangely.

Thanks for replaying, close this for now.
