### ISSUE TITLE
Showing Blank Screen After Payment

### ISSUE THREAD

**Issue by rommansabbir** [razorpay/razorpay-android-sample-app#194]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Android SDK to make sure your issue has not already been fixed. 

## Razorpay SDK Version :
Open `build.gradle`. > Copy `com.razorpay:checkout:1.5.16`

## Android OS Version :
Android 10, API 29

### What you did:

I have tried to make payment with the SDK (Live API Key), after the providing the information & make the payment it's showing the blank screen

### What happened:

![Screenshot_593](https://user-images.githubusercontent.com/25950083/99878109-566bfc00-2c2d-11eb-9b7f-220165cc8e6e.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a transaction with local indian visa number

**Comment by vivekshindhe** [comment]
Hey @rommansabbir 
Could you send us some more details? Like the payload you are sending. and also, if possible could you please try it on an actual device? Also, please use the updated version, 1.6.4

**Comment by rommansabbir** [comment]
Yeah, sure. I will update the dependency & try on real device. Note that: I have created more transaction in LIVE mode, it's working fine, This is a one time issue.

**Comment by sumedht** [comment]
@rommansabbir We also faced this issue & found that this issue is on the emulator only. Maybe a configuration or network related issue based on the environment it is running. On a real device, it's working as expected even in a lower network.
Closing this issue as of now as it's reproducible on an emulator only. Feel free to re-open if u want to add some inputs in this.
