### ISSUE TITLE
Playstore reject app update for policy violation

### ISSUE THREAD

**Issue by rahulsharmagbpec** [razorpay/razorpay-android-sample-app#202]
My application is getting reject from playstore because of policy violation of Intent Redirection,
tried with razorpay version 'com.razorpay:checkout:1.6.5' and 'com.razorpay:checkout:1.6.3'
screen shot is attached for reference from playstore support email
![Screen Shot 2021-01-29 at 10 00 41 AM](https://user-images.githubusercontent.com/12457008/106238649-3e18ee80-6227-11eb-8d9d-352fa48ec6e7.png)

**Comment by vivekshindhe** [comment]
This issue has been resolved by version 1.6.5. In Google app submissions for testing there's a testing track where all versions of the apps are subjected to check. The testing track includes version of the app which has this vulnerability. This is reaffirmed by the message from google. App bundles with versions xxx and xxx have this vulnerability and not the next versions. Removing this should resolve the issue for you.

**Comment by sumedht** [comment]
@rahulsharmagbpec Hopefully this issue got resolved now. If u still facing this issue u can reopen ticket.

**Comment by rahulsharmagbpec** [comment]
yes this is resolved now, thank you

**Comment by Balasubramanian6765** [comment]
Hi am using com.razorpay:checkout:1.6.5 but still I get vulnerability for Intent Redirection from Play store.
How to get rid of this issue. 
![Screenshot 2021-08-09 at 2 09 46 PM](https://user-images.githubusercontent.com/61578163/128679773-012c14c5-16fc-471c-91fe-8efc8f7a3e51.png)

**Comment by vivekshindhe** [comment]
You will need to remove the version affected by this from the track as well. And please update to Razorpay version 1.6.10.
On 9 Aug 2021, 2:10 PM +0530, Balasubramanian K U ***@***.***>, wrote:
> Hi am using com.razorpay:checkout:1.6.5 but still I get vulnerability for Intent Redirection from Play store.
> How to get rid of this issue.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
**IMPORTANT**: The contents of this email and any attachments are 
confidential and protected by applicable laws. If you have received this 
email by mistake, please (i) notify the sender immediately; (ii) delete it 
from your database; and (iii) do not disclose the contents to anyone or 
make copies thereof. Razorpay accepts no liability caused due to any 
inadvertent/ unintentional data transmitted through this email.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Balasubramanian6765** [comment]
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />
            
            What about these above 2 lines are necessary. Pls confirm usage of this

**Comment by vivekshindhe** [comment]
The issue is not about this @Balasubramanian6765

**Comment by Balasubramanian6765** [comment]
Thanks @vivekshindhe

**Comment by Balasubramanian6765** [comment]
Hi @vivekshindhe 
I have uploaded another app of mine to the Play store. Razorpay version 1.6.10. still i get this mail from Play store.Also gave me these link for suggestion https://support.google.com/faqs/answer/9267555 
How to get rid of this issue.
![Screenshot 2021-09-07 at 6 10 38 PM](https://user-images.githubusercontent.com/61578163/132346712-db061e99-39d0-447a-87c1-e1bf834008ee.png)
