### ISSUE TITLE
Google's Sms retriever Auto Read otp is not working for cards payment options in RazorPay  Please look into this

### ISSUE THREAD

**Issue by kedia1307** [razorpay/razorpay-android-sample-app#268]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Android SDK to make sure your issue has not already been fixed. 

## Razorpay SDK Version :
Open `build.gradle`. > Copy `com.razorpay` version here or github URL. 

## Android OS Version :
Any specific android version if this issue is only occuring on a specific version. 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by kedia1307** [comment]
Steps To Reproduce
 select debit card/ credit card option
Enter card credentials and wait for otp
once the otp consent dialog appears click allow
it will not pass otp to the otp field you will have to enter it manually in order to make it work.
I am using sms retriever api from google in my app.

**Comment by ramya12345** [comment]
Its mentioned in the Important Notes of docs>>>>>  https://razorpay.com/docs/payment-gateway/android-integration/standard/
  that 
Due to the changes in the Google Play Developer policy, we have removed auto-read SMS feature from Razorpay Android Standard SDK versions 1.5.1 and higher. However, if your Android app already has permission to read SMS, then Razorpay will auto-read it.
If you are using older versions of Razorpay Android Standard SDK, you must upgrade to the latest version available on the Maven Repository.
![razorpayissue2](https://user-images.githubusercontent.com/18005152/143906282-aba09cc1-ac4a-4a62-a520-07e5d828dd90.png)

**Comment by vivekshindhe** [comment]
@kedia1307 yes. We saw this. Working on a fix. Will update it in the coming versions. Thank you
