### ISSUE TITLE
No error message when internet is not connected

### ISSUE THREAD

**Issue by triveous** [razorpay/razorpay-android-sample-app#7]
Problem: We've encountered a blank white screen when there are internet connectivity issues after selecting a payment method. It would be better if we could show an error message (highlighting connectivity issues) in some way.

Steps to reproduce
1. Select a payment mechanism (good internet connectivity)
![Selecting payment method](http://s32.postimg.org/hlyyz2tj9/Screenshot_20160513_124434.png)
2. Disconnect internet and click on pay
!["Blank screen](http://s32.postimg.org/48n3ocqv9/Screenshot_20160513_124442.png)

**Comment by shashankmehta** [comment]
@triveous You shouldn't be getting a _blank_ screen. The expected behavior is to call the merchant's `onPaymentError` method. So the control should be back to your activity. Is a view attached to your activity?

In any case, I get that it is kind of sub-optimal to have the merchant handle something like an internet related error. It's just that this kind of scenarios were rare, and we have never really been requested for such a feature. Hence, we are thinking of handling it in the following manner, with a more descriptive error message: 

![screenshot_2016-05-13-14-54-14](https://cloud.githubusercontent.com/assets/1315944/15243687/cffbf668-191a-11e6-92b7-56970e9ba0ea.png)

However, please do note that in case of an internet issue in the start itself, when the checkout form is being opened, the error will have to be handled by you.

**Comment by ubarua123** [comment]
Talking on the topic,
@shashankmehta  you said `onPaymentError` will be called if any issue occurs with the error code.
The error codes as written on the documentation are 
![image](https://cloud.githubusercontent.com/assets/8141308/18378842/0b5f6210-768d-11e6-9b12-0473cba0b53a.png)

But I dont see those contants defined anywhere. Am I missing something here? 
P.s - I have the lastest jar.

This is what I get:
![image](https://cloud.githubusercontent.com/assets/8141308/18378895/37533b62-768d-11e6-9d83-16f0a2074fbe.png)

**Comment by steelrooter** [comment]
@ubarua123 The error codes were not `public` and we apologize for the same. This will be fixed in the upcoming release. For Razorpay SDK v0.13.0, you can use the following values for the error codes:
```
static int NETWORK_ERROR = 2;
static int INVALID_OPTIONS = 3;
```
