### ISSUE TITLE
Need RazorPay Flutter Plugin

### ISSUE THREAD

**Issue by shashkiranr** [razorpay/razorpay-android-sample-app#96]
I didn't know where to post this so putting it here. 

It would be great if RazorPay Tech team releases Razorpay plugin for flutter.

**Comment by pronav** [comment]
@shashkiranr let us check and get back about feasibility of an official flutter sdk

**Comment by dynamitechetan** [comment]
I created it since I wanted to use it in my apps.
https://pub.dartlang.org/packages/razorpay_plugin
https://github.com/dynamitechetan/razorpay_flutter/
It works perfectly fine. I am using this in my 2 production apps.
@pronav Can we make it official ?? I am using your official SDKs inside this plugin.

**Comment by pronav** [comment]
That's awesome! a couple suggestions to make plugin more applicable for general use:

1. initial `params` should be passed as general JSON instead of fixed number of options such as name, description and so on. This is needed to support more options in future automatically without having to update flutter plugin.

2. In payment success callbacks, instead of single field - string `payment_id`, whole response should be returned as JSON again. This is to support more fields other than payment_id in success callback, such as order_id, signature etc.

pretty neatly done, overall. I'll create an issue in your repo about making this official SDK and to discuss above mentioned points. Thank you very much for contributing!

**Comment by dynamitechetan** [comment]
@pronav Cool 😎

**Comment by shashkiranr** [comment]
@pronav It would be great if a flutter plugin written using dart. For Android especially it opens up a new activity when using Android RazorPay plugin and this causes issues when certain timed transactions are involved.

**Comment by raveesh-me** [comment]
@pronav it will be really nice of you to maintain an official razorpay plugin for flutter. 

From a business point of view, flutter is taking over all forms of app development to the point that more than half of the app developers in Kolkata are now using flutter.

And no Indian payment gateway provides support for or guidance on how to use razorpay with these platforms. 

@dynamitechetan did an amazing job of writing the plugin but he can't maintain it forever and the plugin keeps crashing from time to time.

**Comment by raveesh-me** [comment]
A very simple solution would be a pure dart package to open checkout page in a webview, which would free even you of the pains of the changing android and ios SDKs

**Comment by umanghome** [comment]
We'll be releasing a Flutter plugin pretty soon. ETA end of this week.

**Comment by raveesh-me** [comment]
Hi! @umanghome can't wait to test it out!

**Comment by raveesh-me** [comment]
Hi! Any updates / new ETAs?

**Comment by umanghome** [comment]
@raveesh-me https://github.com/razorpay/razorpay-flutter 🎉

You would need to use this directly from git for now, we'll publish to Pub soon.

**Comment by raveesh-me** [comment]
awesome

**Comment by vijayawoshe** [comment]
Still there will be the question for plugin maintenance? As raveesh suggested pure dart package with webview would be the nice idea.

**Comment by ChintanAcharya** [comment]
@vijayawoshe Razorpay will be maintaining this plugin.

**Comment by raveesh-me** [comment]
Hi! I've filed two issues. This is a blocking requirement for three of our major projects so please let me know if we can be of any help in the process.

**Comment by sumedht** [comment]
Closing this ticket as there is the flutter SDK available
https://github.com/razorpay/razorpay-flutter
